name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: GHCR Login
      uses: docker/login-action@v3.2.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GHCR_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{github.actor}}/octane:$(date +%s) --tag ghcr.io/${{github.actor}}/octane:latest
    - name: Push the Docker image
      run: docker push ghcr.io/${{github.actor}}/octane --all-tags
