name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: GHCR Login
      uses: docker/login-action@v3.2.0
      with:
        registry: ghcr.io
        username: dissfall
        password: ${{secrets.GHCR_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{vars.GHCR_IMAGE_NAME}}:$(date +%s) --tag ${{vars.GHCR_IMAGE_NAME}}:latest
    - name: Push the Docker image
      run: docker push ${{vars.GHCR_IMAGE_NAME}} --all-tags
